[package]
name = "wasmer-examples/nuxt-wasmer-starter"
version = "0.2.0"
description = "Nuxt static website Wasmer starter package"
readme = "README.md"
repository = "https://github.com/wasmer-examples/nuxt-wasmer-starter"

[dependencies]
"wasmer/winterjs" = "^1.0"

[fs]
"/web" = "dist"

[[command]]
name = "script"
module = "wasmer/winterjs:winterjs"
runner = "wasi"

[command.annotations.wasi]
main-args = ["--mode", "cloudflare", "/web"]